from fastapi import FastAPI, Request, HTTPException
from fastapi.responses import HTMLResponse, FileResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
import os

# ------------------------
# APP INIT
# ------------------------

app = FastAPI(title="GOR://A Backend ASGI")

app.mount("/styles", StaticFiles(directory="templates/styles"), name="styles")
app.mount("/scripts", StaticFiles(directory="templates/scripts"), name="scripts")
app.mount("/assets", StaticFiles(directory="templates/assets"), name="assets")

templates = Jinja2Templates(directory="templates")


# ------------------------
# STATIC PAGE ROUTES (20)
# ------------------------

PAGES = {
    "/": "index.html",
    "/login": "login.html",
    "/signup": "signup.html",
    "/forgot-password": "forgot.html",
    "/settings": "settings.html",
    "/dashboard": "dashboard.html",
    "/workspace": "workspace.html",
    "/pricing": "pricing.html",
    "/help": "help.html",
    "/about": "about.html",
    "/builder": "builder-home.html",
    "/builder/new": "builder-new.html",
    "/builder/import": "builder-import.html",
    "/builder/marketplace": "marketplace.html",
    "/builder/docs": "builder-docs.html",
    "/projects": "projects-list.html",
    "/projects/create": "project-create.html",
}

# Dynamically register static routes
for route, template in PAGES.items():
    async def page(request: Request, template=template): 
        return templates.TemplateResponse(template, {"request": request})
    app.get(route, response_class=HTMLResponse)(page)


# ------------------------
# PROJECT DYNAMIC SYSTEM
# ------------------------

@app.get("/projects/{project_id}", response_class=HTMLResponse)
async def project_detail(request: Request, project_id: str):
    return templates.TemplateResponse(
        "project-detail.html", {"request": request, "project_id": project_id}
    )


@app.get("/projects/{project_id}/editor", response_class=HTMLResponse)
async def project_editor(request: Request, project_id: str, file: str = "index.html"):
    # Pass file name to frontend editor UI
    return templates.TemplateResponse(
        "project-editor.html",
        {"request": request, "project_id": project_id, "file": file}
    )


@app.get("/projects/{project_id}/preview", response_class=HTMLResponse)
async def project_preview(request: Request, project_id: str):
    return templates.TemplateResponse(
        "project-preview.html", {"request": request, "project_id": project_id}
    )


# ------------------------
# DEPLOYED APP SIMULATION
# ------------------------

DEPLOY_DIR = "user_apps"  # dynamic generated files

@app.get("/app/{project_id}/{path:path}")
async def serve_deployed_app(project_id: str, path: str):
    app_path = os.path.join(DEPLOY_DIR, project_id, path)

    if os.path.isdir(app_path):
        app_path = os.path.join(app_path, "index.html")

    if not os.path.exists(app_path):
        raise HTTPException(status_code=404, detail="File not found in deployed app.")

    return FileResponse(app_path)



# ------------------------
# BASIC API ENDPOINTS
# (These will connect to your agent later)
# ------------------------

@app.post("/api/project/{project_id}/save")
async def save_file(project_id: str, file: str, content: str):
    project_dir = os.path.join(DEPLOY_DIR, project_id)
    os.makedirs(project_dir, exist_ok=True)
    file_path = os.path.join(project_dir, file)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    return {"success": True, "file": file}


@app.post("/api/project/{project_id}/generate-file")
async def generate_new_file(project_id: str, filename: str):
    project_dir = os.path.join(DEPLOY_DIR, project_id)
    os.makedirs(project_dir, exist_ok=True)
    file_path = os.path.join(project_dir, filename)
    with open(file_path, "w") as f:
        f.write("<!-- Placeholder generated by AI -->")
    return {"success": True, "generated": filename}
