"""
preview_server.py — gor://a Preview Runner

Flow:
- Writes project files to /tmp/gor-preview/{id}
- Spawns uvicorn subprocess on a dynamic port
- Frontend iframe loads http://localhost:<dynamic_port>/
"""

from __future__ import annotations
import os
import shutil
import subprocess
import uuid
from pathlib import Path
from supabase import create_client, Client

from .settings import get_settings

settings = get_settings()
supabase: Client = create_client(settings.SUPABASE_URL, settings.SUPABASE_SERVICE_ROLE_KEY)

PREVIEW_ROOT = Path("/tmp/gor_preview")


class PreviewManager:
    processes = {}  # project_id -> subprocess handle
    ports_used = {}

    def _assign_port(self, project_id):
        # each preview stays on assigned port
        base_port = 9100
        if project_id in self.ports_used:
            return self.ports_used[project_id]
        port = base_port + len(self.ports_used)
        self.ports_used[project_id] = port
        return port

    def build_tree(self, project_id: uuid.UUID, target: Path):
        # fetch project files
        res = (
            supabase.table("files")
            .select("path,content")
            .eq("project_id", str(project_id))
            .execute()
        )
        os.makedirs(target, exist_ok=True)
        for row in res.data or []:
            dest = target / row["path"]
            dest.parent.mkdir(parents=True, exist_ok=True)
            with open(dest, "w", encoding="utf-8") as f:
                f.write(row["content"])

    def start_preview(self, project_id: uuid.UUID):
        # cleanup old folder
        preview_dir = PREVIEW_ROOT / str(project_id)
        if preview_dir.exists():
            shutil.rmtree(preview_dir)
        preview_dir.mkdir(parents=True, exist_ok=True)

        # write
        self.build_tree(project_id, preview_dir)

        # Stop if already running process
        if project_id in self.processes:
            try:
                self.processes[project_id].kill()
            except:
                pass

        port = self._assign_port(project_id)

        # Spawn uvicorn from preview folder
        # preview folder MUST contain an app.py (generated by the agent)
        process = subprocess.Popen(
            ["uvicorn", "app:app", "--host", "0.0.0.0", f"--port={port}"],
            cwd=str(preview_dir),
        )
        self.processes[project_id] = process
        return port

    def stop_preview(self, project_id: uuid.UUID):
        if project_id in self.processes:
            try:
                self.processes[project_id].kill()
            except:
                pass


preview_manager = PreviewManager()
